version: "3.9"

services:
  redis-stack:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
      - "8001:8001"