
spring:
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  data:
    redis:
      cluster:
        nodes:
          - localhost:6379
        # how often we hop between nodes
        max-redirects: 4
      # timeout for all redis commands (e.g. to retrieve results)
      timeout: 10000
  application:
    name: spring-redis-playground


server:
  port: 8080