
spring:
  data:
    redis:
      sentinel:
        master: myprimary
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
      cluster:
        nodes:
          - valkey-node-primary-0:6379
          - valkey-node-primary-1:6379
          - valkey-node-primary-2:6379
#          - valkey-node-0:6379
#          - valkey-node-1:6379
#          - valkey-node-2:6379
#          - valkey-node-3:6379
#          - valkey-node-4:6379
        max-redirects: 4
      timeout: 10000
  application:
    name: spring-redis-playground


server:
  port: 8080